spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/personnel_management?characterEncoding=utf-8&serverTimezone=GMT%2B8

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml